"""PDF generation service for resumes using ReportLab."""

import os
from datetime import datetime
from typing import Optional
from io import BytesIO

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
from reportlab.pdfgen import canvas

from app.schemas import Resume


class PDFService:
    """Service for generating PDF resumes from Resume documents."""

    # Color scheme - Emerald green theme
    PRIMARY_COLOR = colors.HexColor('#047857')
    ACCENT_COLOR = colors.HexColor('#059669')
    TEXT_COLOR = colors.HexColor('#1f2937')
    LIGHT_GRAY = colors.HexColor('#6b7280')

    @staticmethod
    def generate_pdf(resume: Resume, is_free_user: bool = True) -> bytes:
        """
        Generate PDF from Resume document using ReportLab.

        Args:
            resume: Resume document to convert
            is_free_user: If True, includes "Generated by JobAlert AI" footer

        Returns:
            bytes: PDF file content
        """
        buffer = BytesIO()

        # Create PDF document
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=0.75*inch,
            leftMargin=0.75*inch,
            topMargin=0.6*inch,
            bottomMargin=0.6*inch
        )

        # Build PDF content
        story = []
        content = resume.content

        # Define styles
        styles = getSampleStyleSheet()

        # Custom styles
        name_style = ParagraphStyle(
            'Name',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=PDFService.PRIMARY_COLOR,
            spaceAfter=6,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        )

        contact_style = ParagraphStyle(
            'Contact',
            parent=styles['Normal'],
            fontSize=9,
            textColor=PDFService.LIGHT_GRAY,
            alignment=TA_CENTER,
            spaceAfter=12
        )

        section_title_style = ParagraphStyle(
            'SectionTitle',
            parent=styles['Heading2'],
            fontSize=12,
            textColor=PDFService.PRIMARY_COLOR,
            spaceBefore=12,
            spaceAfter=6,
            fontName='Helvetica-Bold',
            borderWidth=0,
            borderPadding=0,
            leftIndent=0,
            rightIndent=0
        )

        body_style = ParagraphStyle(
            'Body',
            parent=styles['Normal'],
            fontSize=10,
            textColor=PDFService.TEXT_COLOR,
            alignment=TA_JUSTIFY,
            spaceAfter=6
        )

        job_title_style = ParagraphStyle(
            'JobTitle',
            parent=styles['Normal'],
            fontSize=11,
            textColor=PDFService.TEXT_COLOR,
            fontName='Helvetica-Bold',
            spaceAfter=2
        )

        company_style = ParagraphStyle(
            'Company',
            parent=styles['Normal'],
            fontSize=10,
            textColor=PDFService.ACCENT_COLOR,
            fontName='Helvetica-Bold',
            spaceAfter=2
        )

        date_style = ParagraphStyle(
            'Date',
            parent=styles['Normal'],
            fontSize=9,
            textColor=PDFService.LIGHT_GRAY,
            fontName='Helvetica-Oblique',
            spaceAfter=4
        )

        bullet_style = ParagraphStyle(
            'Bullet',
            parent=styles['Normal'],
            fontSize=9,
            textColor=PDFService.TEXT_COLOR,
            leftIndent=20,
            spaceAfter=3,
            bulletIndent=10
        )

        # Header - Name
        story.append(Paragraph(content.full_name, name_style))

        # Contact Info
        contact_parts = []
        if content.email:
            contact_parts.append(content.email)
        if content.phone:
            contact_parts.append(content.phone)
        if content.location:
            contact_parts.append(content.location)
        if content.linkedin_url:
            contact_parts.append(content.linkedin_url)

        # Use HTML entity for bullet separator
        contact_text = " &#8226; ".join(contact_parts)
        story.append(Paragraph(contact_text, contact_style))

        # Horizontal line
        story.append(HRFlowable(
            width="100%",
            thickness=2,
            color=PDFService.PRIMARY_COLOR,
            spaceAfter=12
        ))

        # Professional Summary
        if content.summary:
            story.append(Paragraph("PROFESSIONAL SUMMARY", section_title_style))
            story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#d1d5db'), spaceAfter=6))
            story.append(Paragraph(content.summary, body_style))
            story.append(Spacer(1, 0.1*inch))

        # Technical Skills
        if content.skills:
            story.append(Paragraph("TECHNICAL SKILLS", section_title_style))
            story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#d1d5db'), spaceAfter=6))

            skills_text = ", ".join(content.skills)
            story.append(Paragraph(skills_text, body_style))
            story.append(Spacer(1, 0.1*inch))

        # Professional Experience
        if content.experience:
            story.append(Paragraph("PROFESSIONAL EXPERIENCE", section_title_style))
            story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#d1d5db'), spaceAfter=6))

            for exp in content.experience:
                # Job title
                story.append(Paragraph(exp.get('title', 'Position'), job_title_style))

                # Company
                story.append(Paragraph(exp.get('company', 'Company'), company_style))

                # Date and location
                date_range = ""
                if exp.get('start_date'):
                    start = exp['start_date']
                    end = exp.get('end_date', 'Present')
                    date_range = f"{start} - {end}"

                location = exp.get('location', '')
                date_location = date_range
                if location:
                    date_location = f"{date_range} | {location}"

                story.append(Paragraph(date_location, date_style))

                # Responsibilities as bullets
                if exp.get('responsibilities'):
                    for responsibility in exp['responsibilities']:
                        # Use HTML entity for bullet point to avoid encoding issues
                        bullet_text = f"&#8226; {responsibility}"
                        story.append(Paragraph(bullet_text, bullet_style))

                story.append(Spacer(1, 0.1*inch))

        # Education
        if content.education:
            story.append(Paragraph("EDUCATION", section_title_style))
            story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#d1d5db'), spaceAfter=6))

            for edu in content.education:
                degree_text = f"{edu.get('degree', 'Degree')} in {edu.get('field', 'Field')}"
                story.append(Paragraph(degree_text, job_title_style))

                institution_text = edu.get('institution', 'Institution')
                story.append(Paragraph(institution_text, company_style))

                # Graduation date and GPA
                date_gpa_parts = []
                if edu.get('graduation_year'):
                    date_gpa_parts.append(str(edu['graduation_year']))
                if edu.get('gpa'):
                    date_gpa_parts.append(f"GPA: {edu['gpa']}/5.0")

                if date_gpa_parts:
                    date_gpa_text = " • ".join(date_gpa_parts)
                    story.append(Paragraph(date_gpa_text, date_style))

                story.append(Spacer(1, 0.08*inch))

        # Projects
        if content.projects:
            story.append(Spacer(1, 0.05*inch))
            story.append(Paragraph("KEY PROJECTS", section_title_style))
            story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#d1d5db'), spaceAfter=6))

            for project in content.projects:
                project_name = project.get('name', 'Project')
                story.append(Paragraph(project_name, job_title_style))

                project_desc = project.get('description', '')
                story.append(Paragraph(project_desc, body_style))

                story.append(Spacer(1, 0.08*inch))

        # Certifications
        if content.certifications:
            story.append(Spacer(1, 0.05*inch))
            story.append(Paragraph("CERTIFICATIONS", section_title_style))
            story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#d1d5db'), spaceAfter=6))

            for cert in content.certifications:
                cert_text = cert.get('name', '')
                if cert.get('issuer'):
                    cert_text += f" - {cert['issuer']}"
                if cert.get('date'):
                    cert_text += f" ({cert['date']})"

                # Use HTML entity for bullet point
                bullet_text = f"&#8226; {cert_text}"
                story.append(Paragraph(bullet_text, bullet_style))

        # Footer (only for free users)
        if is_free_user:
            story.append(Spacer(1, 0.3*inch))
            footer_style = ParagraphStyle(
                'Footer',
                parent=styles['Normal'],
                fontSize=7,
                textColor=colors.HexColor('#9ca3af'),
                alignment=TA_CENTER
            )
            footer_text = f"Generated by JobAlert AI on {datetime.now().strftime('%B %d, %Y')}"
            story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#e5e7eb')))
            story.append(Spacer(1, 0.05*inch))
            story.append(Paragraph(footer_text, footer_style))

        # Build PDF
        doc.build(story)

        # Get PDF bytes
        pdf_bytes = buffer.getvalue()
        buffer.close()

        return pdf_bytes

    @staticmethod
    async def save_pdf_to_storage(pdf_bytes: bytes, resume_id: str) -> str:
        """
        Save PDF to storage (local or cloud).

        Returns:
            str: URL to access the PDF
        """
        # For now, save locally
        # TODO: Integrate with Cloudflare R2 or S3

        storage_dir = os.path.join(os.getcwd(), "storage", "resumes")
        os.makedirs(storage_dir, exist_ok=True)

        filename = f"resume_{resume_id}.pdf"
        filepath = os.path.join(storage_dir, filename)

        with open(filepath, 'wb') as f:
            f.write(pdf_bytes)

        # Return a URL (in production, this would be a CDN URL)
        return f"/storage/resumes/{filename}"
