"""Data models for the JobAlert AI application using MongoEngine."""

from mongoengine import (
    Document, EmbeddedDocument,
    StringField, IntField, FloatField, BooleanField, DateTimeField,
    EmailField, ListField, DictField, EmbeddedDocumentField
)
from datetime import datetime
from enum import Enum
import hashlib


# Enums
class MatchStatus(str, Enum):
    NEW = "new"
    SAVED = "saved"
    GENERATING = "generating"
    RESUME_READY = "resume_ready"
    APPLIED = "applied"
    REJECTED = "rejected"


class NotificationFrequency(str, Enum):
    INSTANT = "instant"
    DAILY = "daily"
    WEEKLY = "weekly"
    NEVER = "never"


class ExperienceLevel(str, Enum):
    ENTRY = "entry"
    JUNIOR = "junior"
    MID = "mid"
    SENIOR = "senior"
    LEAD = "lead"
    EXECUTIVE = "executive"


# Embedded Documents (not saved as separate collections)
class WorkExperience(EmbeddedDocument):
    """Work experience entry."""
    company = StringField(required=True)
    title = StringField(required=True)
    location = StringField()
    start_date = StringField()  # YYYY-MM format
    end_date = StringField()  # None for current position
    is_current = BooleanField(default=False)
    bullets = ListField(StringField())


class Education(EmbeddedDocument):
    """Education entry."""
    institution = StringField(required=True)
    degree = StringField(required=True)
    field = StringField()
    graduation_year = IntField()
    gpa = FloatField()


class Certification(EmbeddedDocument):
    """Certification entry."""
    name = StringField(required=True)
    issuer = StringField(required=True)
    issue_date = StringField()
    expiry_date = StringField()
    credential_id = StringField()


class UserProfile(EmbeddedDocument):
    """Embedded user profile information."""
    full_name = StringField(required=True)
    email = EmailField(required=True)
    phone = StringField()
    location = StringField(required=True)
    linkedin_url = StringField()
    github_url = StringField()
    portfolio_url = StringField()

    # Professional info
    current_title = StringField()
    years_of_experience = IntField()
    skills = ListField(StringField(), default=list)

    # Detailed sections
    work_experience = ListField(EmbeddedDocumentField(WorkExperience), default=list)
    education = ListField(EmbeddedDocumentField(Education), default=list)
    certifications = ListField(EmbeddedDocumentField(Certification), default=list)

    # Professional summary
    summary = StringField()


class JobPreferences(EmbeddedDocument):
    """User's job search preferences."""
    desired_roles = ListField(StringField(), default=list)
    desired_locations = ListField(StringField(), default=list)
    remote_preference = StringField(default="any")  # any, remote_only, hybrid, onsite
    min_salary = IntField()
    max_salary = IntField()
    experience_levels = ListField(StringField(), default=list)
    required_keywords = ListField(StringField(), default=list)
    exclude_keywords = ListField(StringField(), default=list)
    exclude_companies = ListField(StringField(), default=list)


class NotificationSettings(EmbeddedDocument):
    """User notification preferences."""
    email_enabled = BooleanField(default=True)
    frequency = StringField(default=NotificationFrequency.DAILY.value)
    min_score_threshold = FloatField(default=60.0)
    digest_time_hour = IntField(default=18)  # 24-hour format
    notify_resume_ready = BooleanField(default=True)


class ScoreBreakdown(EmbeddedDocument):
    """Detailed scoring breakdown for a match."""
    title_score = FloatField(default=0.0)
    skills_score = FloatField(default=0.0)
    location_score = FloatField(default=0.0)
    experience_score = FloatField(default=0.0)
    keyword_score = FloatField(default=0.0)
    salary_score = FloatField(default=0.0)

    # Matched elements
    matched_skills = ListField(StringField(), default=list)
    matched_keywords = ListField(StringField(), default=list)


class ResumeContent(EmbeddedDocument):
    """Structured resume content generated by AI."""
    # Contact Information
    full_name = StringField(required=True)
    email = StringField()
    phone = StringField()
    location = StringField()
    linkedin_url = StringField()
    portfolio_url = StringField()

    # Resume Content
    summary = StringField(required=True)
    skills = ListField(StringField(), default=list)
    experience = ListField(DictField(), default=list)  # Flexible structure
    education = ListField(DictField(), default=list)
    projects = ListField(DictField(), default=list)
    certifications = ListField(DictField(), default=list)

    # Analysis (optional, added during generation)
    keywords_injected = ListField(StringField(), default=list)
    keywords_missing = ListField(StringField(), default=list)
    ats_score = FloatField(default=85.0)  # 0-100 estimated ATS compatibility


# Document Models (saved as MongoDB collections)
class User(Document):
    """User account and profile."""

    # Auth
    email = EmailField(required=True, unique=True)
    hashed_password = StringField(required=True)

    # Profile
    profile = EmbeddedDocumentField(UserProfile, required=True)
    preferences = EmbeddedDocumentField(JobPreferences, default=JobPreferences)
    notification_settings = EmbeddedDocumentField(NotificationSettings, default=NotificationSettings)

    # Status
    is_active = BooleanField(default=True)
    is_verified = BooleanField(default=False)
    onboarding_completed = BooleanField(default=False)
    is_admin = BooleanField(default=False)

    # Credits
    credits = IntField(default=3)  # Free credits
    total_credits_purchased = IntField(default=0)

    # Timestamps
    created_at = DateTimeField(default=datetime.utcnow)
    updated_at = DateTimeField(default=datetime.utcnow)
    last_login = DateTimeField()

    meta = {
        'collection': 'users',
        'indexes': [
            'email',
            'created_at',
        ]
    }


class Job(Document):
    """Job posting from various sources."""

    # Core info
    title = StringField(required=True)
    company = StringField(required=True)
    description = StringField(required=True)
    apply_url = StringField(required=True)

    # Details
    location = StringField()
    remote = BooleanField(default=False)
    salary_min = IntField()
    salary_max = IntField()
    experience_level = StringField()

    # Metadata
    source = StringField(required=True)  # "rss", "api", "user_url"
    source_url = StringField(required=True)
    ats_platform = StringField()  # "greenhouse", "lever", "workday", etc.

    # Processing
    fingerprint = StringField(required=True, unique=True)  # MD5 hash for deduplication
    normalized_description = StringField()
    extracted_skills = ListField(StringField(), default=list)

    # Timestamps
    posted_at = DateTimeField()
    ingested_at = DateTimeField(default=datetime.utcnow)

    meta = {
        'collection': 'jobs',
        'indexes': [
            'fingerprint',
            'company',
            'ingested_at',
            'remote',
        ]
    }

    @staticmethod
    def generate_fingerprint(title: str, company: str, apply_url: str) -> str:
        """Generate unique fingerprint for deduplication."""
        raw = f"{title.lower()}{company.lower()}{apply_url}"
        return hashlib.md5(raw.encode()).hexdigest()


class Match(Document):
    """Scored job match for a user."""

    # References
    user_id = StringField(required=True)
    job_id = StringField(required=True)

    # Score
    overall_score = FloatField(required=True)
    score_breakdown = EmbeddedDocumentField(ScoreBreakdown, required=True)

    # Status
    status = StringField(default=MatchStatus.NEW.value)
    resume_id = StringField()

    # Tracking
    notified_at = DateTimeField()
    viewed_at = DateTimeField()
    applied_at = DateTimeField()

    # Timestamps
    created_at = DateTimeField(default=datetime.utcnow)
    updated_at = DateTimeField(default=datetime.utcnow)

    meta = {
        'collection': 'matches',
        'indexes': [
            'user_id',
            'job_id',
            ('user_id', 'job_id'),  # Compound index
            'status',
            'overall_score',
            'created_at',
        ]
    }


class Resume(Document):
    """AI-generated tailored resume."""

    # References
    user_id = StringField(required=True)
    match_id = StringField(required=True)
    job_id = StringField(required=True)

    # Content
    content = EmbeddedDocumentField(ResumeContent, required=True)

    # Files
    pdf_url = StringField()
    pdf_key = StringField()  # S3 object key

    # Metadata
    generation_time_seconds = FloatField()
    tokens_used = IntField()
    ats_score = FloatField()

    # Timestamps
    created_at = DateTimeField(default=datetime.utcnow)

    meta = {
        'collection': 'resumes',
        'indexes': [
            'user_id',
            'match_id',
            'job_id',
            'created_at',
        ]
    }


class Notification(Document):
    """Email notification tracking."""

    # References
    user_id = StringField(required=True)

    # Type and content
    notification_type = StringField(required=True)  # "daily_digest", "instant_alert", "resume_ready"
    subject = StringField(required=True)

    # Matches included (for digests/alerts)
    match_ids = ListField(StringField(), default=list)

    # Delivery
    sent_at = DateTimeField(default=datetime.utcnow)
    sendgrid_message_id = StringField()

    # Engagement tracking
    opened_at = DateTimeField()
    clicked_at = DateTimeField()

    meta = {
        'collection': 'notifications',
        'indexes': [
            'user_id',
            'notification_type',
            'sent_at',
        ]
    }


class Payment(Document):
    """Payment transaction record."""

    # References
    user_id = StringField(required=True)

    # Stripe
    stripe_session_id = StringField()
    stripe_payment_intent_id = StringField()

    # Details
    amount_cents = IntField(required=True)
    credits_purchased = IntField(required=True)
    product_type = StringField(required=True)  # "single", "5pack", "unlimited"

    # Status
    status = StringField(default="pending")  # "pending", "completed", "failed", "refunded"

    # Timestamps
    created_at = DateTimeField(default=datetime.utcnow)
    completed_at = DateTimeField()

    meta = {
        'collection': 'payments',
        'indexes': [
            'user_id',
            'stripe_session_id',
            'status',
            'created_at',
        ]
    }


class FeedSource(Document):
    """Dynamic RSS/XML feed sources for job scraping."""

    # Feed details
    name = StringField(required=True)
    url = StringField(required=True, unique=True)
    feed_type = StringField(required=True)  # "rss", "greenhouse", "lever"

    # For company-specific feeds (Greenhouse/Lever)
    company_token = StringField()  # Used for Greenhouse/Lever company identifiers

    # Status
    is_active = BooleanField(default=True)
    last_scraped_at = DateTimeField()
    last_scrape_success = BooleanField(default=True)
    last_scrape_error = StringField()

    # Stats
    total_jobs_scraped = IntField(default=0)
    last_scrape_job_count = IntField(default=0)

    # Timestamps
    created_at = DateTimeField(default=datetime.utcnow)
    updated_at = DateTimeField(default=datetime.utcnow)
    created_by = StringField()  # Admin user ID who added this feed

    meta = {
        'collection': 'feed_sources',
        'indexes': [
            'url',
            'is_active',
            'feed_type',
            'last_scraped_at',
        ]
    }
